### ISSUE TITLE
Cannot find module or its corresponding type declarations

### ISSUE THREAD

**Issue by awdr74100** [tobiasdiez/nuxt-graphql-server#70] opened 2023-09-10 17:07 UTC
![螢幕擷取畫面 2023-09-11 005820](https://github.com/tobiasdiez/nuxt-graphql-server/assets/47501692/276706b6-71c7-4d3a-9f64-c2e908c70292)
![螢幕擷取畫面 2023-09-11 010412](https://github.com/tobiasdiez/nuxt-graphql-server/assets/47501692/444c691d-ce0b-4884-8aa3-008868e64025)

The actual problem is just like the title, the `#graphql/resolver` and `#graphql/schema` module cannot find its corresponding declaration.

Guess it might be related to the recent update of nuxt?

Thanks in advance for your help!

**Comment by tobiasdiez** [comment] 2023-09-11 00:26
Duplicate of #71.

**Closed by tobiasdiez** 2023-09-11 00:26 UTC
