### ISSUE TITLE
Module import & Endpoint error

### ISSUE THREAD

**Issue by amersb29** [tobiasdiez/nuxt-graphql-server#57] opened 2023-05-25 22:37 UTC
Hi. 
I've added your module and I'm running in an error importing the **schema** from the virtual module _#graphql/schema_.

The error said: _The requested module '~/.nuxt/graphql-schema.mjs' does not provide an export named 'schema'_

At times the scheme is null and at others it is not. 
I verified this by printing the object returned by the module to the console.

Also when trying to access the _/api/graphql_ endpoint, I saw the following error:

 ERROR  [h3] [unhandled] write EPIPE
  at afterWriteDispatched (node:internal/stream_base_commons:160:15)
  at writeGeneric (node:internal/stream_base_commons:151:3)
  at Socket._writeGeneric (node:net:905:11)
  at Socket.connect (node:net:887:12)
  at Object.onceWrapper (node:events:627:28)
  at Socket.emit (node:events:525:35)
  at Socket.emit (node:domain:489:12)
  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1263:10)

OS: Win10
Node versions tested: 18.16.0, 16.20.0 & 14.21.3 

`  
  "devDependencies": {
    "@types/node": "^18",
    "nuxt": "^3.5.1"
  },
  "dependencies": {
    "@apollo/server": "^4.7.1",
    "@as-integrations/h3": "^1.1.5",
    "graphql": "^16.6.0",
    "nuxt-graphql-server": "^2.0.0"
  }
`

**Comment by tobiasdiez** [comment] 2023-05-26 01:42
Can you please give me the content of the file `.nuxt/graphql-schema.mjs` when its not working?

> At times the scheme is null and at others it is not.

Do you have an idea when its not working? Could it be that you sometimes run say the `npm dev` command from a subfolder?

**Comment by amersb29** [comment] 2023-05-29 21:42
Hi Tobias.
The file content becomes intermittent. At times it's empty (and that is when it marks the error) and suddenly it has the code with the schema.
![TfD24m7Sy5](https://github.com/tobiasdiez/nuxt-graphql-server/assets/19498499/7e028e96-f3ed-4cf9-9d69-6dccfcb9c5f1)

I'm running the `yarn dev` command from the root folder and I'm just trying to make a HelloWorld example.

_~/server/api/graphql.ts_
```
import { Resolvers } from '#graphql/resolver';
import { schema } from '#graphql/schema';
import { ApolloServer, BaseContext, ContextFunction } from '@apollo/server';
import {
  H3ContextFunctionArgument,
  H3HandlerOptions,
  startServerAndCreateH3Handler,
} from '@as-integrations/h3';

const resolvers: Resolvers = {
  Query: {
    hello: () => 'Hello world!',
  },
};

console.log('TypeDefs ::: ', schema);

const apollo: ApolloServer<BaseContext> = new ApolloServer({
  typeDefs: schema,
  resolvers,
});

const context: ContextFunction<[H3ContextFunctionArgument], BaseContext> = (
  event
): Promise<BaseContext> => {
  return new Promise<BaseContext>(() => {
    console.log('Context Event ::: ', event);
  });
};

const options: H3HandlerOptions<BaseContext> = {
  context,
};

export default startServerAndCreateH3Handler(apollo, options);

```

~/server/graphql/hello.graphql
```
type Query {
  hello: String
}
```

**Comment by tobiasdiez** [comment] 2023-05-30 03:42
This looks very strange, and I never experienced something like this before. My guess is that some file watcher is updating the graphql schema in the background, which then triggers the HMR. Do you have a git extension running in the background, or is your code in dropbox or something similar?

What you can try is to locally uncomment https://github.com/tobiasdiez/nuxt-graphql-server/blob/9d81c92bb7ff8535ec291eb6a740baf77a20e6e8/src/module.ts#L109-L118 (in your node-modules folder, find the nuxt-graphql-server addin and then this code should be under the dist folder). If you feel investing a bit more time, you can also set a debug breakpoint in https://github.com/tobiasdiez/nuxt-graphql-server/blob/9d81c92bb7ff8535ec291eb6a740baf77a20e6e8/src/module.ts#L66 and see when this method is called. It should only be called once at the beginning, and then every time you change your schema file.

Sorry that I have to put the debug work on your shoulders, but I sadly cannot reproduce this here on my system.

**Comment by tobiasdiez** [comment] 2023-09-15 14:40
Closing this in the hope that it's fixed by https://github.com/tobiasdiez/nuxt-graphql-server/pull/68.

**Closed by tobiasdiez** 2023-09-15 14:40 UTC
Labels: bug
